import React,{useEffect,useMemo,useState}from'react';
import{useNavigate}from'react-router-dom';
import{arrayRemove,arrayUnion,collection,doc,getDoc,getDocs,query,setDoc,where}from'firebase/firestore';
import{db}from'../firebase';
import{useAuth}from'../contexts/AuthContext';
import type{Listing,Rating}from'../types';

const typeLabels:Record<Listing['type'],string>={swap:'Swap',donate:'Free',sell:'Sell'};
const normalizeImages=(images?:unknown):string[]=>Array.isArray(images)?images.filter((image):image is string=>typeof image==='string').map(image=>image.trim()).filter(Boolean):[];
const formatCompactPrice=(amount:number)=>{if(amount>=1000000)return`KSh ${(amount/1000000).toFixed(amount%1000000===0?0:1)}M`;if(amount>=1000)return`KSh ${(amount/1000).toFixed(amount%1000===0?0:1)}K`;return`KSh ${amount.toLocaleString()}`};
const formatListingValue=(listing:Listing)=>{if(listing.type==='sell'){const amount=Number(listing.price||0);return amount>0?formatCompactPrice(amount):'For Sale'}return typeLabels[listing.type]};
const RatingStars:React.FC<{average:number;count:number}>=({average,count})=>{const safeAverage=Math.max(0,Math.min(5,average||0));return <span className="inline-flex items-center gap-1"><span className="inline-flex shrink-0 items-center gap-0.5" aria-label={`${safeAverage.toFixed(1)} out of 5 stars`}>{[0,1,2,3,4].map(index=>{const fill=Math.max(0,Math.min(1,safeAverage-index))*100;return <span key={index} className="relative inline-block h-[14px] w-[14px] leading-none"><span className="absolute inset-0 text-[14px] leading-none text-stone-300">★</span><span className="absolute inset-0 overflow-hidden text-[14px] leading-none text-[#F59E0B]" style={{width:`${fill}%`}}>★</span></span>})}</span><span className="text-stone-500">({count})</span></span>};

const BookCard:React.FC<{listing:Listing}>=({listing})=>{
 const navigate=useNavigate();
 const{currentUser,userProfile,refreshProfile}=useAuth();
 const[currentImageIndex,setCurrentImageIndex]=useState(0);
 const[bookmarking,setBookmarking]=useState(false);
 const[failedImages,setFailedImages]=useState<string[]>([]);
 const[sellerPhoto,setSellerPhoto]=useState(listing.userPhoto||'');
 const[sellerRating,setSellerRating]=useState<{average:number;count:number}>({average:0,count:0});
 const profileBookmarked=Boolean(currentUser&&userProfile?.bookmarks?.includes(listing.id));
 const[localBookmarked,setLocalBookmarked]=useState(profileBookmarked);
 const images=useMemo(()=>normalizeImages(listing.images).filter(image=>!failedImages.includes(image)),[listing.images,failedImages]);
 const activeImage=images[currentImageIndex]||images[0];
 const hasImages=Boolean(activeImage);
 const listingValue=formatListingValue(listing);
 const hasReviews=sellerRating.count>0;
 useEffect(()=>{setCurrentImageIndex(0);setFailedImages([]);setSellerRating({average:0,count:0})},[listing.id]);
 useEffect(()=>{setLocalBookmarked(profileBookmarked)},[profileBookmarked,listing.id]);
 useEffect(()=>{const sync=(event:Event)=>{const detail=(event as CustomEvent<{listingId:string;bookmarked:boolean}>).detail;if(detail?.listingId===listing.id)setLocalBookmarked(detail.bookmarked)};window.addEventListener('reshelved:bookmark-updated',sync);return()=>window.removeEventListener('reshelved:bookmark-updated',sync)},[listing.id]);
 useEffect(()=>{if(currentImageIndex>=images.length)setCurrentImageIndex(0)},[images.length,currentImageIndex]);
 useEffect(()=>{setSellerPhoto(listing.userPhoto||'')},[listing.userPhoto]);
 useEffect(()=>{const fetchSellerMeta=async()=>{if(!listing.userId)return;try{const publicSnap=await getDoc(doc(db,'publicProfiles',listing.userId)).catch(()=>null);if(publicSnap?.exists()){const data=publicSnap.data();if(typeof data.photoURL==='string'&&data.photoURL.trim())setSellerPhoto(data.photoURL)}const userSnap=await getDoc(doc(db,'users',listing.userId)).catch(()=>null);if(userSnap?.exists()){const userData=userSnap.data();const photoURL=userData.photoURL;if(typeof photoURL==='string'&&photoURL.trim()){setSellerPhoto(photoURL);if(currentUser?.uid===listing.userId&&photoURL!==listing.userPhoto){await setDoc(doc(db,'listings',listing.id),{userPhoto:photoURL},{merge:true}).catch(()=>undefined);await setDoc(doc(db,'publicProfiles',listing.userId),{uid:listing.userId,displayName:userData.displayName||listing.userName||'Reshelved user',photoURL,location:userData.location||listing.location||'',updatedAt:Date.now()},{merge:true}).catch(()=>undefined)}}}const ratingsSnap=await getDocs(query(collection(db,'ratings'),where('toUserId','==',listing.userId))).catch(()=>null);if(ratingsSnap){const ratings:Rating[]=[];ratingsSnap.forEach(item=>ratings.push({id:item.id,...item.data()}as Rating));if(ratings.length>0){setSellerRating({average:ratings.reduce((sum,rating)=>sum+(rating.rating||0),0)/ratings.length,count:ratings.length})}else setSellerRating({average:0,count:0})}}catch(err){console.error('Error loading seller card data:',err);setSellerRating({average:0,count:0})}};fetchSellerMeta()},[listing.userId,listing.id,listing.userPhoto,currentUser?.uid]);
 useEffect(()=>{if(images.length<=1)return;const interval=window.setInterval(()=>setCurrentImageIndex(current=>(current+1)%images.length),3800);return()=>window.clearInterval(interval)},[images.length]);
 const handleImageError=(image:string)=>setFailedImages(current=>current.includes(image)?current:[...current,image]);
 const handleCardClick=()=>navigate(`/listing/${listing.id}`);
 const publishBookmarkState=(bookmarked:boolean)=>window.dispatchEvent(new CustomEvent('reshelved:bookmark-updated',{detail:{listingId:listing.id,bookmarked}}));
 const handleBookmark=async(event:React.MouseEvent<HTMLButtonElement>)=>{event.preventDefault();event.stopPropagation();if(!currentUser||bookmarking)return;const next=!localBookmarked;setLocalBookmarked(next);publishBookmarkState(next);setBookmarking(true);try{await setDoc(doc(db,'users',currentUser.uid),{bookmarks:next?arrayUnion(listing.id):arrayRemove(listing.id),lastSeen:Date.now()},{merge:true});await refreshProfile()}catch(err){console.error('Error updating bookmark:',err);setLocalBookmarked(!next);publishBookmarkState(!next)}finally{setBookmarking(false)}};
 return <article onClick={handleCardClick} role="link" tabIndex={0} onKeyDown={event=>{if(event.key==='Enter'||event.key===' '){event.preventDefault();handleCardClick()}}} className="group block h-full cursor-pointer overflow-hidden rounded-[22px] border border-stone-200 bg-white p-3 shadow-sm transition-shadow duration-300 hover:border-stone-300 hover:shadow-xl">
  <div className="relative aspect-[1.42/1] overflow-hidden rounded-[11px] bg-stone-100">
   {hasImages?images.map((image,index)=><img key={image} src={image} alt={index===currentImageIndex?listing.title:''} aria-hidden={index!==currentImageIndex} className={`absolute inset-0 h-full w-full bg-stone-100 object-cover transition-opacity duration-[1100ms] ease-[cubic-bezier(0.22,1,0.36,1)] ${index===currentImageIndex?'opacity-100':'opacity-0'}`} loading={index===0?'eager':'lazy'} onError={()=>handleImageError(image)}/>):<div className="absolute inset-0 flex h-full w-full items-center justify-center bg-stone-100"><i className="las la-book-open text-5xl text-stone-300"/></div>}
   {hasReviews&&<div className="absolute left-3 top-3 flex cursor-default items-center gap-1 rounded-[4px] bg-white/95 p-[4px] text-[13px] font-bold leading-none text-stone-800 shadow-sm"><i className="las la-star text-[13px] leading-none text-[#F7AF31]"/><span>{sellerRating.average.toFixed(1)}</span></div>}
   {currentUser&&<button type="button" onClick={handleBookmark} disabled={bookmarking} aria-label={localBookmarked?'Remove from favorites':'Save to favorites'} aria-pressed={localBookmarked} className="absolute right-3 top-3 flex h-6 w-6 cursor-pointer items-center justify-center border-0 bg-transparent p-0 text-white shadow-none outline-none ring-0 disabled:cursor-not-allowed disabled:opacity-60"><i className={`${localBookmarked?'text-primary-600':'text-white'} las la-heart text-[24px] leading-none opacity-100`}/></button>}
   {images.length>1&&<div className="absolute bottom-3 left-1/2 flex -translate-x-1/2 items-center gap-1.5">{images.map((image,index)=><span key={`${image}-${index}`} className={`block h-1.5 w-1.5 rounded-full bg-white shadow-sm transition-opacity duration-300 ${index===currentImageIndex?'opacity-100':'opacity-55'}`} />)}</div>}
  </div>
  <div className="px-1 pb-1 pt-4"><h3 className="reshelved-book-card-title line-clamp-1 font-['Work_Sans'] text-[17px] font-bold leading-tight text-stone-950 transition group-hover:text-primary-700">{listing.title}</h3><p className="mt-1 line-clamp-1 text-[14px] text-stone-500">by {listing.author}</p><div className="mt-4 flex items-center gap-2 text-[14px] font-semibold text-stone-950"><i className="las la-map-marker-alt shrink-0 text-[18px] leading-none text-stone-950"/><span className="line-clamp-1">{listing.location}, Nairobi</span></div><div className="mt-4 grid grid-cols-[minmax(0,1fr)_auto_minmax(0,1fr)] divide-x divide-stone-200 text-stone-800"><div className="flex min-w-0 items-center justify-center gap-1.5 px-2 py-1.5"><i className="las la-book-open shrink-0 text-[15px] leading-none text-stone-700 sm:text-[16px]"/><span className="min-w-0 truncate text-[14px] font-semibold text-stone-800 sm:text-[13px]">{listing.condition}</span></div><div className="flex shrink-0 items-center justify-center gap-1.5 px-2.5 py-1.5"><i className="las la-tag shrink-0 text-[15px] leading-none text-stone-700 sm:text-[16px]"/><span className="whitespace-nowrap text-[14px] font-semibold text-stone-800 sm:text-[13px]">{listingValue}</span></div><div className="flex min-w-0 items-center justify-center gap-1.5 px-2 py-1.5"><i className="las la-layer-group shrink-0 text-[15px] leading-none text-stone-700 sm:text-[16px]"/><span className="min-w-0 truncate text-[14px] font-semibold text-stone-800 sm:text-[13px]">{listing.category}</span></div></div><div className="mt-5 flex items-center gap-3 border-t border-stone-200 pt-4">{sellerPhoto?<img src={sellerPhoto} alt={listing.userName} className="h-9 w-9 rounded-full bg-stone-100 object-cover"/>:<div className="flex h-9 w-9 items-center justify-center rounded-full bg-stone-100 text-xs font-bold text-stone-500">{listing.userName?.[0]?.toUpperCase()||'U'}</div>}<div className="min-w-0"><p className="truncate text-sm text-stone-500">Listed by <span className="font-bold text-stone-800">{listing.userName||'Reshelved user'}</span></p><p className="mt-0.5 text-[13px] font-semibold leading-none text-[#F59E0B]">{hasReviews?<RatingStars average={sellerRating.average} count={sellerRating.count}/>:<span className="text-stone-400">No reviews yet</span>}</p></div></div></div>
 </article>;
};
export default BookCard;